name: "build"

on:
  pull_request:
    paths-ignore:
      - ".docs/**"
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4' ]

      fail-fast: false

    name: PHP ${{ matrix.php }} tests
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, mbstring, xml, tokenizer
          coverage: none

      - run: composer install --no-interaction --prefer-source
      - run: vendor/bin/tester tests -s -C
      - if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: tests/PdfResponse/output

  lowest_dependencies:
    name: Lowest Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2
          extensions: json, mbstring, xml, tokenizer
          coverage: none

      - run: composer update --no-interaction --prefer-dist --prefer-lowest --prefer-stable
      - run: vendor/bin/tester tests -s -C


  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: json, mbstring, xml, tokenizer, xdebug
          coverage: none

      - run: mkdir -p tests/tmp
      - run: composer install --no-progress --prefer-dist
      - run: wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      - run: vendor/bin/tester -p phpdbg tests -s -C --coverage ./coverage.xml --coverage-src ./src
      - run: php coveralls.phar --verbose --config tests/.coveralls.yml
